### PR TITLE
update to apiX and 7.0 (hotfix)

### PR DESCRIPTION
**Pull request by nopjmp**
While I'm here, just switch to use the Dalamud bootstrap targets instead of specifying the settings manually

The signature matches two functions, but I can't find where the second function is even called. I only have Binary Ninja, so I had to make sure the signature by hand.

### CODE REVIEW

**Comment by nopjmp** [comment]
`E8 ?? ?? ?? ?? 33 C0 E9 ?? ?? ?? ?? 41 8B C6` this works as well, but one of my friends and static member was still having the device pausing problem without this plugin, so I think it is still needed. I've looked into what other system do to detect changes and it might be better if we could hook the WndProc message event listener and then validate the WM_DEVICECHANGE message like those systems do instead of just calling the controller count api via sharpdx.

**Comment by pardalrp92** [comment]
Do you have any news in regards to this pull request? 
I don't think @Jessidhia is still maintaining this plugin.

**Comment by caitlyn-gg** [comment]
I've verified that the signature provided by nopjmp (`E8 ?? ?? ?? ?? 33 C0 E9 ?? ?? ?? ?? 41 8B C6`) is still valid as of the latest update.

**Comment by reiichi001** [comment]
Per XIVLauncher and Dalamud discord, this plugin is no longer being maintained and is up for adoption. (According to Jessidhia, SE 'fixed' the bug, unless they didn't actually cover all their cases).
https://discord.com/channels/581875019861328007/653504487352303619/1257664906736701490

So if you're interested in adopting it, @nopjmp, you can submit an update to the [main repo](https://github.com/goatcorp/DalamudPluginsD17) directly.

**Comment by caitlyn-gg** [comment]
> Per XIVLauncher and Dalamud discord, this plugin is no longer being maintained and is up for adoption. (According to Jessidhia, SE 'fixed' the bug, unless they didn't actually cover all their cases). https://discord.com/channels/581875019861328007/653504487352303619/1257664906736701490
> 
> So if you're interested in adopting it, @nopjmp, you can submit an update to the [main repo](https://github.com/goatcorp/DalamudPluginsD17) directly.  
  
  
I actually reached out to Jess around a week ago to let them know people were still having issues and to inquire about this plugin and was told that she could check into it once she's home from traveling:
> Strange; we tried to find the signature again in #plugin-dev right after 7.0 but the code seemed to have been entirely rewritten in the engine (I also could no longer cause the issue with my usual testing method of unplugging/replugging a yubikey, and a friend who had frequent controller issues pre-7.0 also reported it seemed fixed) so I assumed it was entirely fixed by their dualsense-supporting rewrite.
> I'm traveling so I can't look into it atm but I'll be back on wednesday / thursday.

**Comment by nopjmp** [comment]
It's most likely working now, it could be that my friend was suffering from "other issues" and this did help bandaid it but we have not tested recently nor have I have it any mind, I think I told them to disable it while triaging a stuttering problem they were having and they have not told me of controller disconnect issues.

Most likely there was a bug at launch, but was resolved. If anyone else thinks there is an issue they should triage it with Square Enix.

**Pull request closed without merging**
